spring:
  application:
  name: library

  datasource:
  url: jdbc:mysql://localhost:3306/library
  username: root
  password: dsova2207_12
  driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
     hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
server:
  post: 8083

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256

