
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - libraryspring_app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - libraryspring_app-network


  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
        - libraryspring_app-network


  library:
    build:
      context: ./library
    image: library
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/library"
       SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
       SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
       SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
       KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - mysql
      - kafka
    networks:
      - libraryspring_app-network

  libraryservice:
    build:
      context: ./libraryservice
    image: libraryservice
    ports:
      - "8082:8082"
    environment:
       SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/freebookservice"
       SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
       SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
       SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
       KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - mysql
      - kafka
    networks:
      - libraryspring_app-network

  authservice:
    build:
      context: ./authservice
    image: authservice
    ports:
      - "8083:8083"
    environment:
       SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/security_db"
       SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
       SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
       SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - mysql
    networks:
      - libraryspring_app-network
volumes:
 mysql_data:

networks:
 libraryspring_app-network:
  driver: bridge
