services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=library'
      - 'MYSQL_PASSWORD=dsova2207_12'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'
